# -*- coding: utf-8 -*-

# using language code following ISO 639
# two letter codes correspond to ISO 639-1
# three letter codes correspond to ISO 639-2/B
# https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

languages = {"": ["", ""],
             "abkhazian": ["abk", "ab"],
             "afar": ["aar", "aa"],
             "afrikaans": ["afr", "af"],
             "akan": ["aka", "ak"],
             "albanian": ["alb", "sq"],
             "amharic": ["amh", "am"],
             "arabic": ["ara", "ar"],
             "aragonese": ["arg", "an"],
             "armenian": ["arm", "hy"],
             "assamese": ["asm", "as"],
             "avaric": ["ava", "av"],
             "avestan": ["ave", "ae"],
             "aymara": ["aym", "ay"],
             "azerbaijani": ["aze", "az"],
             "bambara": ["bam", "bm"],
             "bashkir": ["bak", "ba"],
             "basque": ["baq", "eu"],
             "belarusian": ["bel", "be"],
             "bengali": ["ben", "bn"],
             "bihari languages": ["bih", "bh"],
             "bislama": ["bis", "bi"],
             "bosnian": ["bos", "bs"],
             "breton": ["bre", "br"],
             "bulgarian": ["bul", "bg"],
             "burmese": ["bur", "my"],
             "catalan": ["cat", "ca"],
             "chamorro": ["cha", "ch"],
             "chechen": ["che", "ce"],
             "chichewa": ["nya", "ny"],
             "chinese": ["chi", "zh"],
             "chuvash": ["chv", "cv"],
             "cornish": ["cor", "kw"],
             "corsican": ["cos", "co"],
             "cree": ["cre", "cr"],
             "croatian": ["hrv", "hr"],
             "czech": ["cze", "cs"],
             "danish": ["dan", "da"],
             "divehi": ["div", "dv"],
             "dutch": ["dut", "nl"],
             "dzongkha": ["dzo", "dz"],
             "english": ["eng", "en"],
             "esperanto": ["epo", "eo"],
             "estonian": ["est", "et"],
             "ewe": ["ewe", "ee"],
             "faroese": ["fao", "fo"],
             "fijian": ["fij", "fj"],
             "finnish": ["fin", "fi"],
             "french": ["fre", "fr"],
             "fulah": ["ful", "ff"],
             "galician": ["glg", "gl"],
             "georgian": ["geo", "ka"],
             "german": ["ger", "de"],
             "greek": ["gre", "el"],
             "guarani": ["grn", "gn"],
             "gujarati": ["guj", "gu"],
             "haitian": ["hat", "ht"],
             "hausa": ["hau", "ha"],
             "hebrew": ["heb", "he"],
             "herero": ["her", "hz"],
             "hindi": ["hin", "hi"],
             "hiri motu": ["hmo", "ho"],
             "hungarian": ["hun", "hu"],
             "interlingua": ["ina", "ia"],
             "indonesian": ["ind", "id"],
             "interlingue": ["ile", "ie"],
             "irish": ["gle", "ga"],
             "igbo": ["ibo", "ig"],
             "inupiaq": ["ipk", "ik"],
             "ido": ["ido", "io"],
             "icelandic": ["ice", "is"],
             "italian": ["ita", "it"],
             "inuktitut": ["iku", "iu"],
             "japanese": ["jpn", "ja"],
             "javanese": ["jav", "jv"],
             "kalaallisut": ["kal", "kl"],
             "kannada": ["kan", "kn"],
             "kanuri": ["kau", "kr"],
             "kashmiri": ["kas", "ks"],
             "kazakh": ["kaz", "kk"],
             "central khmer": ["khm", "km"],
             "kikuyu": ["kik", "ki"],
             "kinyarwanda": ["kin", "rw"],
             "kirghiz": ["kir", "ky"],
             "komi": ["kom", "kv"],
             "kongo": ["kon", "kg"],
             "korean": ["kor", "ko"],
             "kurdish": ["kur", "ku"],
             "kuanyama": ["kua", "kj"],
             "latin": ["lat", "la"],
             "luxembourgish": ["ltz", "lb"],
             "ganda": ["lug", "lg"],
             "limburgan": ["lim", "li"],
             "lingala": ["lin", "ln"],
             "lao": ["lao", "lo"],
             "lithuanian": ["lit", "lt"],
             "luba-katanga": ["lub", "lu"],
             "latvian": ["lav", "lv"],
             "manx": ["glv", "gv"],
             "macedonian": ["mac", "mk"],
             "malagasy": ["mlg", "mg"],
             "malay": ["may", "ms"],
             "malayalam": ["mal", "ml"],
             "maltese": ["mlt", "mt"],
             "maori": ["mao", "mi"],
             "marathi": ["mar", "mr"],
             "marshallese": ["mah", "mh"],
             "mongolian": ["mon", "mn"],
             "nauru": ["nau", "na"],
             "navajo": ["nav", "nv"],
             "north ndebele": ["nde", "nd"],
             "nepali": ["nep", "ne"],
             "ndonga": ["ndo", "ng"],
             "norwegian bokmål": ["nob", "nb"],
             "norwegian nynorsk": ["nno", "nn"],
             "norwegian": ["nor", "no"],
             "sichuan yi": ["iii", "ii"],
             "south ndebele": ["nbl", "nr"],
             "occitan": ["oci", "oc"],
             "ojibwa": ["oji", "oj"],
             "church slavic": ["chu", "cu"],
             "oromo": ["orm", "om"],
             "oriya": ["ori", "or"],
             "ossetian": ["oss", "os"],
             "panjabi": ["pan", "pa"],
             "pali": ["pli", "pi"],
             "persian": ["per", "fa"],
             "polish": ["pol", "pl"],
             "pashto": ["pus", "ps"],
             "portuguese": ["por", "pt"],
             "quechua": ["que", "qu"],
             "romansh": ["roh", "rm"],
             "rundi": ["run", "rn"],
             "romanian": ["rum", "ro"],
             "russian": ["rus", "ru"],
             "sanskrit": ["san", "sa"],
             "sardinian": ["srd", "sc"],
             "sindhi": ["snd", "sd"],
             "northern sami": ["sme", "se"],
             "samoan": ["smo", "sm"],
             "sango": ["sag", "sg"],
             "serbian": ["srp", "sr"],
             "gaelic": ["gla", "gd"],
             "shona": ["sna", "sn"],
             "sinhala": ["sin", "si"],
             "slovak": ["slo", "sk"],
             "slovenian": ["slv", "sl"],
             "somali": ["som", "so"],
             "southern sotho": ["sot", "st"],
             "spanish": ["spa", "es"],
             "sundanese": ["sun", "su"],
             "swahili": ["swa", "sw"],
             "swati": ["ssw", "ss"],
             "swedish": ["swe", "sv"],
             "tamil": ["tam", "ta"],
             "telugu": ["tel", "te"],
             "tajik": ["tgk", "tg"],
             "thai": ["tha", "th"],
             "tigrinya": ["tir", "ti"],
             "tibetan": ["tib", "bo"],
             "turkmen": ["tuk", "tk"],
             "tagalog": ["tgl", "tl"],
             "tswana": ["tsn", "tn"],
             "tonga": ["ton", "to"],
             "turkish": ["tur", "tr"],
             "tsonga": ["tso", "ts"],
             "tatar": ["tat", "tt"],
             "twi": ["twi", "tw"],
             "tahitian": ["tah", "ty"],
             "uighur": ["uig", "ug"],
             "ukrainian": ["ukr", "uk"],
             "urdu": ["urd", "ur"],
             "uzbek": ["uzb", "uz"],
             "venda": ["ven", "ve"],
             "vietnamese": ["vie", "vi"],
             "volapük": ["vol", "vo"],
             "walloon": ["wln", "wa"],
             "welsh": ["wel", "cy"],
             "wolof": ["wol", "wo"],
             "western frisian": ["fry", "fy"],
             "xhosa": ["xho", "xh"],
             "yiddish": ["yid", "yi"],
             "yoruba": ["yor", "yo"],
             "zhuang": ["zha", "za"],
             "zulu": ["zul", "zu"]
             }
